version: '3'

services:

  mysql:
    image: mysql:5.6
    container_name: deploy-database
    command: --default-authentication-plugin=mysql_native_password
    network_mode: 'host'
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: 54643db08bcac5c8dd4da17bdebf0d75
    volumes:
      - /tmp/mysql_data:/var/lib/mysql

  semaphore:
    # image: ansiblesemaphore/semaphore:prod-compose
    container_name: semaphore
    network_mode: 'host'
    build:
      context: ./../../../
      dockerfile: ./deployment/docker/prod/Dockerfile
    environment:
      SEMAPHORE_PORT: 9330
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: 54643db08bcac5c8dd4da17bdebf0d75
      SEMAPHORE_DB_HOST: '0.0.0.0'
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: 0f13d5383e33
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      # SEMAPHORE_WEB_ROOT: http://localhost:3002
    depends_on:
      - mysql
  # semaphore_proxy:
  #   image: ansiblesemaphore/proxy:latest
  #   build:
  #     context: ./proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - semaphore
